name: Orchestrate Build & Deploy

on:
  workflow_dispatch:  # Allows manual triggering from the GitHub UI
  repository_dispatch:
    types: [dependency_updated]  # Custom event type for IaC repos

jobs:
  who-triggered-me:
    runs-on: ubuntu-latest
    steps:
      - name: Who triggered me?
        run: |
          echo "### This pipeline trigger summary 🚀" >> $GITHUB_STEP_SUMMARY
          echo "I was triggered by ${{ github.event_name }}" >> $GITHUB_STEP_SUMMARY
          if [ "${{ github.event_name }}" == "repository_dispatch" ]; then
            echo "Triggered by: ${{ github.event.client_payload.triggered_by }}" >> $GITHUB_STEP_SUMMARY
            echo 'Repository Dispatch payload:' >> $GITHUB_STEP_SUMMARY
            echo '```json' >> $GITHUB_STEP_SUMMARY
            echo '${{ toJson(github.event.client_payload) }}' | jq . >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
          elif [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "Manual trigger" >> $GITHUB_STEP_SUMMARY

  deploy_infrastructure:
    runs-on: ubuntu-22.04
    needs: who-triggered-me
    environment: production
    steps:
      - run: echo "Simulating Infrastructure Deployment..."  # Simulate deployment or any other action
      - run: |
          echo "Simulated deployment would occur here."
